version: 2.1

jobs:

  build:
    docker:
      - image: node:19-alpine3.15
    steps:
      - checkout # git clone <my repo>
      - run:
          name: "Build the service"
          command: |
            cd calculator
            pwd
            ls
            npm install
            npm run build
      - persist_to_workspace:
          root: .
          paths:
            - calculator/node_modules



  test:
    docker:
      - image: node:19-alpine3.15
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: "Test the service"
          command: |
            cd calculator
            npm run test


workflows:
  welcome:
    jobs:
      - build
      - test:
          requires:
            - build